### PR TITLE
Fixes #105 #106 #107

### LINKED ISSUE #105: Update the Electron to latest version
**Actual Behaviour**

Electron version is not updated the version 1.7.8 has security flaws so the electron version should be updated to 1.8.2

**Expected Behaviour**

Electron version should be the latest version

##### Please check the applicable fields -

- [x] I ensure that this issue is not a duplicate of any current open issues(s).
- [x] Assign this issue to me (I want to work on this).
- [x] I will send my PR only after I'm assigned to this issue by any maintainer.
- [x] I understand that I will be unassigned from this issue if I fail to send a PR for this within a week.

I will update it to the latest version in my PR.

In future we can look for implementing automatic dependecies update.

### LINKED ISSUE #107: We should use yarn instead of npm
**Actual Behaviour**

Instead of npm we should use yarn. As its new and better.

**Expected Behaviour**

Yarn should be used as the package manager in the app.

##### Please check the applicable fields -

- [x] I ensure that this issue is not a duplicate of any current open issues(s).
- [x] Assign this issue to me (I want to work on this).
- [x] I will send my PR only after I'm assigned to this issue by any maintainer.
- [x] I understand that I will be unassigned from this issue if I fail to send a PR for this within a week.

@anshumanv need your views for it.

Will bundle up everything in a single PR if you give a thumbsup to do it.

### PR DESCRIPTION
**Pull request by ms10398**
yarn is added, now links open in default browser and electron is upadted to latest version

 Fixes #107 #106 #105 

#### By submitting this pull request I confirm I've read and complied with the below declarations.
- [x] I have tested the changes locally and they are functional.
- [x] I ensure that I sent this pull request after being assigned to the corresponding issue.
- [x] This pull request has a descriptive title. For example, `Added/Fixed {Feature/Bug}`, not `Update README.md` or `Added new code`.
- [x] This pull request will be closed if I fail to update it even once in a continuous time span of 7 days.

@anshumanv Have a look at it

### CODE REVIEW

**Comment by anshumanv** [comment]
Yay! :smile:

**Comment by ms10398** [comment]
Lol If I pass codacy Travis will fail and if I pass travis codacy will fail as one requires single quotes and other requires double quotes.

@anshumanv

**Comment by BrainBuzzer** [comment]
Look at issue #109 
If you want to do it now let us know about it. Your PR will be merged as soon as that issue is closed.

**Comment by ms10398** [comment]
I will add that too today in a while 
with a PR and then let this PR rebuilt and reanalysed by codacy :smile:

**Comment by anshumanv** [comment]
Oh :laughing: @ms10398 
xo config is presently in package.json https://github.com/fossasia/susi_desktop/blob/a3118be658fec18ab3f67d7b1a6539ca2af291aa/package.json#L42, probably we can have a separate config file which enforces rules that both of them pass.

**Comment by ms10398** [comment]
Codacy takes a eslintrc file if its present in root I was thinking to let xo be like that and add eslintrc so that codacy takes the configuration of it

Whats your thought?

**Comment by anshumanv** [comment]
Cool, let's add an eslintrc then. :smile: @ms10398

**Comment by ms10398** [comment]
So Is that okay for you @BrainBuzzer 

As I read if eslintrc or jshintrc is present then codacy takes its configuration to analyze the project

**Comment by BrainBuzzer** [comment]
Can you change the file with requested code review on Codacy? Or does it break travis again?

**Comment by ms10398** [comment]
Finally it passed :sweat_smile: @BrainBuzzer @anshumanv

**Comment by anshumanv** [comment]
We can infact include package-lock.json in .gitignore since we now have a yarn.lock file.
What say @ms10398 ?

**Comment by ms10398** [comment]
Added @anshumanv :+1:

**Pull request merged**
