### PR TITLE
Basic Electron environment

### PR DESCRIPTION
**Pull request by ankitrgadiya**
Changes
- Added Basic electron environment
- Added Basic app
- Changed README.md

### CODE REVIEW

**Comment by mariobehling** [comment]
Thank you.

**Comment by ankitrgadiya** [comment]
@mariobehling I used LGPL 2.1 licence as used in Susi_server, is it right??

**Comment by mariobehling** [comment]
Sure. Thanks.

**Comment by hongquan** [comment]
Please pay more attention to coding style
selection_089

**Comment by ankitrgadiya** [comment]
@hongquan Sorry for late reply, I'm very new to JS sorry for this.

**Comment by BrainBuzzer** [comment]
Please do not submit any more PRs till I publish a complete working prototype. Thanks

**Pull request merged**
