### PR TITLE
fixes #69, Added a loading gif while webview is loading

### LINKED ISSUE #69: Display a gif while webview is loading
Currently it looks just like a browser is opening some page, to give it a more desktop like feel we need to incorporate a loading gif while the web content is actually loading.

- [x] I ensure that this issue is not a duplicate of any current open issues(s).
- [x] Assign this issue to me (I want to work on this).
- [ ] I will send my PR only after I'm assigned to this issue by any maintainer.
- [x] I understand that I will be unassigned from this issue if I fail to send a PR for this within a week.

### PR DESCRIPTION
**Pull request by anshumanv**
Fixes #69 

#### By submitting this pull request I confirm I've read and complied with the below declarations.
- [x] I have tested the changes locally and they are functional.
- [x] I ensure that I sent this pull request after being assigned to the corresponding issue.
- [x] This pull request has a descriptive title. For example, `Added/Fixed {Feature/Bug}`, not `Update README.md` or `Added new code`.
- [x] This pull request will be closed if I fail to update it even once in a continuous time span of 7 days.

Demo:
susi-demo

### CODE REVIEW

**Comment by anshumanv** [comment]
Can someone help fix the build log ?

**Comment by anshumanv** [comment]
@BrainBuzzer you can merge this if you can't help, I'm unable to fix the build.

**Comment by mariobehling** [comment]
Please fix travis. It is not building.

**Comment by anshumanv** [comment]
@mariobehling fixed the travis build. :+1:

**Pull request merged**
