### PR TITLE
fixes #27 - Added a switch theme option

### LINKED ISSUE #27: Add Switch Theme Option
Current UI only gives one option of theme. We want to implement a new theme switcher option which will let us choose between themes.

### PR DESCRIPTION
**Pull request by djmgit**
Added a switch theme option by which user can choose between light theme
and dark theme

### CODE REVIEW

**Comment by djmgit** [comment]
@BrainBuzzer I have added a new menu option with two items : light and dark for the respective themes.
I created a custom application menu as I was unable to add new menu item to the default menu bar. However I have kept the new menu bar almost similar to the default one.

**Comment by djmgit** [comment]
light theme :

screenshot from 2017-02-08 17-36-05

**Comment by djmgit** [comment]
screenshot from 2017-02-08 17-36-37

**Comment by djmgit** [comment]
dark theme :

screenshot from 2017-02-08 17-36-25

**Comment by BrainBuzzer** [comment]
No problem. There is another one feature that I desperately want which even more UI customization in Settings section which is to implemented. For now, it seems working.

**Comment by djmgit** [comment]
@BrainBuzzer cool, I would love to work on it once you create the issue :)

**Pull request merged**
