### PR TITLE
UI improvement

### PR DESCRIPTION
**Pull request by ankitrgadiya**
#8 
- Changed background
- Changed input box design
- Changed button design
- New bubble design for messages

screenshot from 2017-01-20 19-18-00

screenshot from 2017-01-20 19-20-06

screenshot from 2017-01-20 19-18-14

screenshot from 2017-01-20 19-19-45

### CODE REVIEW

**Comment by ankitrgadiya** [comment]
@BrainBuzzer Once #9 is merged, we can remove send button completely as no one's gonna use it anyway. What do you think?

**Comment by BrainBuzzer** [comment]
It will be quite good. Make update to your code to remove those buttons.

**Comment by ankitrgadiya** [comment]
OKay let me remove it.

**Comment by ankitrgadiya** [comment]
screenshot from 2017-01-21 11-33-22

**Comment by mariobehling** [comment]
Good job!

**Pull request merged**
