### PR TITLE
fixes #29 - Implemented Toolbar

### LINKED ISSUE #29: Implement a Toolbar
capture

This is what we want to implement next. A toolbar that will have two different options where one will be switch theme and other will be settings. Please use FontAwesome or whatever library you feel suitable but make sure it is open to everyone.

### PR DESCRIPTION
**Pull request by djmgit**
Implemented a toolbar with two items, theme switcher and settings

### CODE REVIEW

**Comment by djmgit** [comment]
presently the settings option does not do anything

**Comment by djmgit** [comment]
screenshot from 2017-02-08 17-36-05

**Comment by djmgit** [comment]
screenshot from 2017-02-13 01-59-13

**Comment by djmgit** [comment]
screenshot from 2017-02-13 01-59-18

**Comment by djmgit** [comment]
screenshot from 2017-02-13 02-01-10

**Comment by BrainBuzzer** [comment]
Looks great :) Settings page is to be implemented later.

**Pull request merged**
